server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://geomet-dev-02.cmc.ec.gc.ca:9080/features/
    basepath: /features
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: en-CA
    cors: true
    pretty_print: true
    limit: 10

logging:
    level: DEBUG
#    logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: Meteorological Service of Canada Geospatial Web Services
        description: The weather can have an incredible influence on our daily lives. It affects the growth of crops and the availability of water. It dictates which regions of the world are habitable or uninhabitable
        keywords:
            - Weather
            - Meteorology
            - Climate
            - Forecasting
            - Floods
            - Weather alerts
            - Storms
            - Wind
            - Temperature
            - Precipitations
            - Snow
            - Ice
        keywords_type: theme
        terms_of_service: None
        url: https://www.canada.ca/en/services/environment/weather.html
    license:
        name: Environment and Climate Change Canada Data Server End-use Licence
        url: http://dd.weather.gc.ca/doc/LICENCE_GENERAL.txt
    provider:
        name: Government of Canada, Environment and Climate Change Canada, Meteorological Service of Canada
        url: https://www.canada.ca/en/services/environment/weather.html
    contact:
        name: Government of Canada, Environment and Climate Change Canada, Meteorological Service of Canada
        position: Service Channel
        address: 77 Westmorland Street, Suite 260
        city: Fredericton
        stateorprovince: New Brunswick
        postalcode: E3B 6Z3
        country: Canadal
        phone: None
        fax: +01-506-451-6010
        email: ecweather-meteo@ec.gc.ca
        url: https://weather.gc.ca/mainmenu/contact_us_e.html
        hours: Monday to Friday, 1300h - 2100h UTC
        instructions: During hours of service
        role: pointOfContact

datasets:
    hydrometric-stations:
        title: Hydrometric Stations
        description: Hydrometric Stations
        keywords:
            - kw1
            - kw2
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: Water Level and Flow - Environment Canada
              href: https://wateroffice.ec.gc.ca
            - type: text/html
              rel: download
              title: download data
              href: https://www.canada.ca/en/environment-climate-change/services/water-overview/quantity/monitoring/survey/data-products-services/national-archive-hydat.html
        extents:
            spatial:
                bbox: [-180,-90,180,90]
            temporal:
                begin: 2011-11-11
                end: now  # or empty
        provider:
            name: Elasticsearch
            data: http://localhost:9200/hydrometric_stations/FeatureCollection
            id_field: IDENTIFIER

    hydrometric-daily-mean:
        title: Hydrometric Daily Mean
        description: Hydrometric Daily Mean
        keywords:
            - kw1
            - kw2
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: Water Level and Flow - Environment Canada
              href: https://wateroffice.ec.gc.ca
            - type: text/html
              rel: download
              title: download data
              href: https://www.canada.ca/en/environment-climate-change/services/water-overview/quantity/monitoring/survey/data-products-services/national-archive-hydat.html
        extents:
            spatial:
                bbox: [-180,-90,180,90]
            temporal:
                begin: 2011-11-11
                end: now  # or empty
        provider:
            name: Elasticsearch
            data: http://localhost:9200/hydrometric_daily_mean/FeatureCollection
            id_field: IDENTIFIER
            time_field: DATE

    hydrometric-monthly-mean:
        title: Hydrometric Monthly Mean
        description: Hydrometric Monthly Mean
        keywords:
            - kw1
            - kw2
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: Water Level and Flow - Environment Canada
              href: https://wateroffice.ec.gc.ca
            - type: text/html
              rel: download
              title: download data
              href: https://www.canada.ca/en/environment-climate-change/services/water-overview/quantity/monitoring/survey/data-products-services/national-archive-hydat.html
        extents:
            spatial:
                bbox: [-180,-90,180,90]
            temporal:
                begin: 2011-11-11
                end: now  # or empty
        provider:
            name: Elasticsearch
            data: http://localhost:9200/hydrometric_monthly_mean/FeatureCollection
            id_field: IDENTIFIER

    hydrometric-annual-statistics:
        title: Hydrometric Annual maximum and minimum daily data
        description: Hydrometric Annual maximum and minimum daily data
        keywords:
            - kw1
            - kw2
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: Water Level and Flow - Environment Canada
              href: https://wateroffice.ec.gc.ca
            - type: text/html
              rel: download
              title: download data
              href: https://www.canada.ca/en/environment-climate-change/services/water-overview/quantity/monitoring/survey/data-products-services/national-archive-hydat.html
        extents:
            spatial:
                bbox: [-180,-90,180,90]
            temporal:
                begin: 2011-11-11
                end: now  # or empty
        provider:
            name: Elasticsearch
            data: http://localhost:9200/hydrometric_annual_statistics/FeatureCollection
            id_field: IDENTIFIER

    hydrometric-annual-peaks:
        title: Hydrometric Annual maximum and minimum instantaneous data
        description: Hydrometric Annual maximum and minimum instantaneous data
        keywords:
            - kw1
            - kw2
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: Water Level and Flow - Environment Canada
              href: https://wateroffice.ec.gc.ca
            - type: text/html
              rel: download
              title: download data
              href: https://www.canada.ca/en/environment-climate-change/services/water-overview/quantity/monitoring/survey/data-products-services/national-archive-hydat.html
        extents:
            spatial:
                bbox: [-180,-90,180,90]
            temporal:
                begin: 2011-11-11
                end: now  # or empty
        provider:
            name: Elasticsearch
            data: http://localhost:9200/hydrometric_annual_peaks/FeatureCollection
            id_field: IDENTIFIER
