components:
  parameters:
    id:
      description: The id of a feature
      in: path
      name: id
      required: true
      schema:
        type: string
    limit:
      description: The optional limit parameter limits the number of items that are
        presented in the response document. Only items are counted that are on the
        first level of the collection in the response document. Nested objects contained
        within the explicitly requested items shall not be counted. Minimum = 1. Maximum
        = 10000. Default = 10.
      explode: false
      in: query
      name: limit
      required: false
      schema:
        default: 10
        maximum: 10000
        minimum: 1
        type: integer
      style: form
info:
  contact:
    email: ecweather-meteo@ec.gc.ca
    name: Government of Canada, Environment and Climate Change Canada, Meteorological
      Service of Canada
    url: https://www.canada.ca/en/services/environment/weather.html
  description: The weather can have an incredible influence on our daily lives. It
    affects the growth of crops and the availability of water. It dictates which regions
    of the world are habitable or uninhabitable
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: None
  title: Meteorological Service of Canada Geospatial Web Services
  version: 3.0.1
  x-keywords:
  - Weather
  - Meteorology
  - Climate
  - Forecasting
  - Floods
  - Weather alerts
  - Storms
  - Wind
  - Temperature
  - Precipitations
  - Snow
  - Ice
openapi: 3.0.1
paths:
  /:
    get:
      description: API
      responses:
        200:
          description: successful operation
      summary: API
      tags:
      - server
  /api:
    get:
      description: This document
      responses:
        200:
          description: successful operation
      summary: This document
      tags:
      - server
  /collections:
    get:
      description: Feature Collections
      responses:
        200:
          description: successful operation
      summary: Feature Collections
      tags:
      - server
  /collections/hydrometric-annual-peaks:
    get:
      description: Hydrometric Annual maximum and minimum instantaneous data
      responses:
        200:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: not found
      summary: Get feature collection metadata
      tags:
      - hydrometric-annual-peaks
  /collections/hydrometric-annual-peaks/items:
    get:
      description: Hydrometric Annual maximum and minimum instantaneous data
      parameters:
      - $ref: '#/components/parameters/limit'
      - explode: false
        in: query
        name: UNITS_FR
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: STATION_NUMBER
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: SYMBOL_EN
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: TIMEZONE_OFFSET
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: DATA_TYPE_FR
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: PEAK_CODE_EN
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: UNITS_EN
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: DATE
        required: false
        schema:
          type: date
        style: form
      - explode: false
        in: query
        name: IDENTIFIER
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: PEAK_CODE_FR
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: DATA_TYPE_EN
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: STATION_NAME
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: SYMBOL_FR
        required: false
        schema:
          type: string
        style: form
      responses:
        200:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: not found
      summary: Get Hydrometric Annual maximum and minimum instantaneous data features
      tags:
      - hydrometric-annual-peaks
  /collections/hydrometric-annual-peaks/items/{id}:
    get:
      description: Hydrometric Annual maximum and minimum instantaneous data
      parameters:
      - $ref: '#/components/parameters/id'
      responses:
        200:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: not found
      summary: Get Hydrometric Annual maximum and minimum instantaneous data feature
        by ID
      tags:
      - hydrometric-annual-peaks
  /collections/hydrometric-annual-statistics:
    get:
      description: Hydrometric Annual maximum and minimum daily data
      responses:
        200:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: not found
      summary: Get feature collection metadata
      tags:
      - hydrometric-annual-statistics
  /collections/hydrometric-annual-statistics/items:
    get:
      description: Hydrometric Annual maximum and minimum daily data
      parameters:
      - $ref: '#/components/parameters/limit'
      - explode: false
        in: query
        name: STATION_NUMBER
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: IDENTIFIER
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: MAX_SYMBOL_FR
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: MIN_SYMBOL_EN
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: MIN_VALUE
        required: false
        schema:
          type: float
        style: form
      - explode: false
        in: query
        name: DATA_TYPE_FR
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: MIN_DATE
        required: false
        schema:
          type: date
        style: form
      - explode: false
        in: query
        name: MAX_SYMBOL_EN
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: MAX_DATE
        required: false
        schema:
          type: date
        style: form
      - explode: false
        in: query
        name: MAX_VALUE
        required: false
        schema:
          type: float
        style: form
      - explode: false
        in: query
        name: STATION_NAME
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: DATA_TYPE_EN
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: MIN_SYMBOL_FR
        required: false
        schema:
          type: string
        style: form
      responses:
        200:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: not found
      summary: Get Hydrometric Annual maximum and minimum daily data features
      tags:
      - hydrometric-annual-statistics
  /collections/hydrometric-annual-statistics/items/{id}:
    get:
      description: Hydrometric Annual maximum and minimum daily data
      parameters:
      - $ref: '#/components/parameters/id'
      responses:
        200:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: not found
      summary: Get Hydrometric Annual maximum and minimum daily data feature by ID
      tags:
      - hydrometric-annual-statistics
  /collections/hydrometric-daily-mean:
    get:
      description: Hydrometric Daily Mean
      responses:
        200:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: not found
      summary: Get feature collection metadata
      tags:
      - hydrometric-daily-mean
  /collections/hydrometric-daily-mean/items:
    get:
      description: Hydrometric Daily Mean
      parameters:
      - $ref: '#/components/parameters/limit'
      - explode: false
        in: query
        name: STATION_NUMBER
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: LEVEL
        required: false
        schema:
          type: float
        style: form
      - explode: false
        in: query
        name: LEVEL_SYMBOL_EN
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: FLOW
        required: false
        schema:
          type: float
        style: form
      - explode: false
        in: query
        name: FLOW_SYMBOL_EN
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: DATE
        required: false
        schema:
          type: date
        style: form
      - explode: false
        in: query
        name: LEVEL_SYMBOL_FR
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: FLOW_SYMBOL_FR
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: STATION_NAME
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: IDENTIFIER
        required: false
        schema:
          type: string
        style: form
      responses:
        200:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: not found
      summary: Get Hydrometric Daily Mean features
      tags:
      - hydrometric-daily-mean
  /collections/hydrometric-daily-mean/items/{id}:
    get:
      description: Hydrometric Daily Mean
      parameters:
      - $ref: '#/components/parameters/id'
      responses:
        200:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: not found
      summary: Get Hydrometric Daily Mean feature by ID
      tags:
      - hydrometric-daily-mean
  /collections/hydrometric-monthly-mean:
    get:
      description: Hydrometric Monthly Mean
      responses:
        200:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: not found
      summary: Get feature collection metadata
      tags:
      - hydrometric-monthly-mean
  /collections/hydrometric-monthly-mean/items:
    get:
      description: Hydrometric Monthly Mean
      parameters:
      - $ref: '#/components/parameters/limit'
      - explode: false
        in: query
        name: STATION_NUMBER
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: MONTHLY_MEAN_LEVEL
        required: false
        schema:
          type: float
        style: form
      - explode: false
        in: query
        name: DATE
        required: false
        schema:
          type: date
        style: form
      - explode: false
        in: query
        name: STATION_NAME
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: IDENTIFIER
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: MONTHLY_MEAN_FLOW
        required: false
        schema:
          type: float
        style: form
      responses:
        200:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: not found
      summary: Get Hydrometric Monthly Mean features
      tags:
      - hydrometric-monthly-mean
  /collections/hydrometric-monthly-mean/items/{id}:
    get:
      description: Hydrometric Monthly Mean
      parameters:
      - $ref: '#/components/parameters/id'
      responses:
        200:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: not found
      summary: Get Hydrometric Monthly Mean feature by ID
      tags:
      - hydrometric-monthly-mean
  /collections/hydrometric-stations:
    get:
      description: Hydrometric Stations
      responses:
        200:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: not found
      summary: Get feature collection metadata
      tags:
      - hydrometric-stations
  /collections/hydrometric-stations/items:
    get:
      description: Hydrometric Stations
      parameters:
      - $ref: '#/components/parameters/limit'
      - explode: false
        in: query
        name: CONTRIBUTOR_FR
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: STATUS_EN
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: STATION_NUMBER
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: CONTRIBUTOR_EN
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: VERTICAL_DATUM
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: STATUS_FR
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: STATION_NAME
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: IDENTIFIER
        required: false
        schema:
          type: string
        style: form
      - explode: false
        in: query
        name: PROV_TERR_STATE_LOC
        required: false
        schema:
          type: string
        style: form
      responses:
        200:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: not found
      summary: Get Hydrometric Stations features
      tags:
      - hydrometric-stations
  /collections/hydrometric-stations/items/{id}:
    get:
      description: Hydrometric Stations
      parameters:
      - $ref: '#/components/parameters/id'
      responses:
        200:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: not found
      summary: Get Hydrometric Stations feature by ID
      tags:
      - hydrometric-stations
  /conformance:
    get:
      description: API conformance definition
      responses:
        200:
          description: successful operation
      summary: API conformance definition
      tags:
      - server
servers:
- description: The weather can have an incredible influence on our daily lives. It
    affects the growth of crops and the availability of water. It dictates which regions
    of the world are habitable or uninhabitable
  url: http://geomet-dev-02.cmc.ec.gc.ca:9080/pygeoapi/
tags:
- description: The weather can have an incredible influence on our daily lives. It
    affects the growth of crops and the availability of water. It dictates which regions
    of the world are habitable or uninhabitable
  externalDocs:
    description: information
    url: https://www.canada.ca/en/services/environment/weather.html
  name: server
- description: Hydrometric Monthly Mean
  name: hydrometric-monthly-mean
- description: Hydrometric Annual maximum and minimum instantaneous data
  name: hydrometric-annual-peaks
- description: Hydrometric Annual maximum and minimum daily data
  name: hydrometric-annual-statistics
- description: Hydrometric Stations
  name: hydrometric-stations
- description: Hydrometric Daily Mean
  name: hydrometric-daily-mean

