server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://geo.wxod-dev.cmc.ec.gc.ca/geomet/features/
    basepath: /geomet/features
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: en-CA
    # cors: true
    pretty_print: true
    limit: 10
    # templates: /path/to/templates

logging:
    level: ERROR
    # logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: Meteorological Service of Canada Geospatial Web Services
        description: The weather can have an incredible influence on our daily lives. It affects the growth of crops and the availability of water. It dictates which regions of the world are habitable or uninhabitable
        keywords:
            - Weather
            - Meteorology
            - Climate
            - Forecasting
            - Floods
            - Weather alerts
            - Storms
            - Wind
            - Temperature
            - Precipitations
            - Snow
            - Ice
        keywords_type: theme
        terms_of_service: None
        url: https://www.canada.ca/en/services/environment/weather.html
    license:
        name: Environment and Climate Change Canada Data Server End-use Licence
        url: http://dd.weather.gc.ca/doc/LICENCE_GENERAL.txt
    provider:
        name: Government of Canada, Environment and Climate Change Canada, Meteorological Service of Canada
        url: https://www.canada.ca/en/services/environment/weather.html
    contact:
        name: Government of Canada, Environment and Climate Change Canada, Meteorological Service of Canada
        position: Service Channel
        address: 77 Westmorland Street, Suite 260
        city: Fredericton
        stateorprovince: New Brunswick
        postalcode: E3B 6Z3
        country: Canadal
        phone: None
        fax: +01-506-451-6010
        email: ecweather-meteo@ec.gc.ca
        url: https://weather.gc.ca/mainmenu/contact_us_e.html
        hours: Monday to Friday, 1300h - 2100h UTC
        instructions: During hours of service
        role: pointOfContact

datasets:
    hydrometric-stations:
        title: Hydrometric Monitoring Stations
        description: A station is a site on a river or lake where water quantity (water level and flow) are collected and recorded.
        keywords: [station, hydrometric station]
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: Water Level and Flow - Environment Canada
              href: https://wateroffice.ec.gc.ca
              hreflang: en-CA
            - type: text/html
              rel: canonical
              title: Niveau d'eau et débit - Environnement Canada
              href: https://wateroffice.ec.gc.ca/index_f.html
              hreflang: fr-CA
            - type: text/html
              rel: download
              title: "National water data archive: HYDAT - Canada.ca"
              href: https://www.canada.ca/en/environment-climate-change/services/water-overview/quantity/monitoring/survey/data-products-services/national-archive-hydat.html
              hreflang: en-CA
            - type: text/html
              rel: download
              title: "Archives nationales des données hydrologiques : HYDAT - Canada.ca"
              href: https://www.canada.ca/fr/environnement-changement-climatique/services/eau-apercu/volume/surveillance/releves/produits-donnees-services/archives-nationales-hydat.html
              hreflang: fr-CA
            - type: application/zip
              rel: download
              title: download data
              href: http://collaboration.cmc.ec.gc.ca/cmc/hydrometrics/www/Hydat_sqlite3_20180417.zip
              hreflang: en-CA
        extents:
            spatial:
                bbox: [-142, 52, -52, 84]
            temporal:
                begin: 1850-01-01
                end: now  # or empty
        provider:
            name: Elasticsearch
            data: http://localhost:9200/hydrometric_stations/FeatureCollection
            id_field: IDENTIFIER

    hydrometric-daily-mean:
        title: Daily Mean of Water Level or Flow
        description: The daily mean is the average of all unit values for a given day.
        keywords: [Daily, Daily Mean, Water Level, Flow, Discharge]
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: Water Level and Flow - Environment Canada
              href: https://wateroffice.ec.gc.ca
              hreflang: en-CA
            - type: text/html
              rel: canonical
              title: Niveau d'eau et débit - Environnement Canada
              href: https://wateroffice.ec.gc.ca/index_f.html
              hreflang: fr-CA
            - type: text/html
              rel: download
              title: "National water data archive: HYDAT - Canada.ca"
              href: https://www.canada.ca/en/environment-climate-change/services/water-overview/quantity/monitoring/survey/data-products-services/national-archive-hydat.html
              hreflang: en-CA
            - type: text/html
              rel: download
              title: "Archives nationales des données hydrologiques : HYDAT - Canada.ca"
              href: https://www.canada.ca/fr/environnement-changement-climatique/services/eau-apercu/volume/surveillance/releves/produits-donnees-services/archives-nationales-hydat.html
              hreflang: fr-CA
            - type: application/zip
              rel: download
              title: download data
              href: http://collaboration.cmc.ec.gc.ca/cmc/hydrometrics/www/Hydat_sqlite3_20180417.zip
              hreflang: en-CA
        extents:
            spatial:
                bbox: [-142, 52, -52, 84]
            temporal:
                begin: 1850-01-01
                end: now  # or empty
        provider:
            name: Elasticsearch
            data: http://localhost:9200/hydrometric_daily_mean/FeatureCollection
            id_field: IDENTIFIER
            time_field: DATE

    hydrometric-monthly-mean:
        title: Monthly Mean of Water Level or Flow
        description: The monthly mean is the average of daily mean values for a given month.
        keywords: [Monthly, Monthly Mean, Water Level, Flow, Discharge]
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: Water Level and Flow - Environment Canada
              href: https://wateroffice.ec.gc.ca
              hreflang: en-CA
            - type: text/html
              rel: canonical
              title: Niveau d'eau et débit - Environnement Canada
              href: https://wateroffice.ec.gc.ca/index_f.html
              hreflang: fr-CA
            - type: text/html
              rel: download
              title: "National water data archive: HYDAT - Canada.ca"
              href: https://www.canada.ca/en/environment-climate-change/services/water-overview/quantity/monitoring/survey/data-products-services/national-archive-hydat.html
            - type: text/html
              rel: download
              title: "Archives nationales des données hydrologiques : HYDAT - Canada.ca"
              href: https://www.canada.ca/fr/environnement-changement-climatique/services/eau-apercu/volume/surveillance/releves/produits-donnees-services/archives-nationales-hydat.html
              hreflang: fr-CA
            - type: application/zip
              hreflang: en-CA
              rel: download
              title: download data
              href: http://collaboration.cmc.ec.gc.ca/cmc/hydrometrics/www/Hydat_sqlite3_20180417.zip
              hreflang: en-CA
        extents:
            spatial:
                bbox: [-142, 52, -52, 84]
            temporal:
                begin: 1850-01-01
                end: now  # or empty
        provider:
            name: Elasticsearch
            data: http://localhost:9200/hydrometric_monthly_mean/FeatureCollection
            id_field: IDENTIFIER

    hydrometric-annual-statistics:
        title: Annual Maximum and Minimum Daily Water Level or Flow
        description: The annual maximum and minimum daily data are the maximum and minimum daily mean values for a given year.
        keywords: [Annual maximum, Annual Minimum, Water Level, Flow, Discharge]
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: Water Level and Flow - Environment Canada
              href: https://wateroffice.ec.gc.ca
              hreflang: en-CA
            - type: text/html
              rel: canonical
              title: Niveau d'eau et débit - Environnement Canada
              href: https://wateroffice.ec.gc.ca/index_f.html
              hreflang: fr-CA
            - type: text/html
              rel: download
              title: "National water data archive: HYDAT - Canada.ca"
              href: https://www.canada.ca/en/environment-climate-change/services/water-overview/quantity/monitoring/survey/data-products-services/national-archive-hydat.html
              hreflang: en-CA
            - type: text/html
              rel: download
              title: "Archives nationales des données hydrologiques : HYDAT - Canada.ca"
              href: https://www.canada.ca/fr/environnement-changement-climatique/services/eau-apercu/volume/surveillance/releves/produits-donnees-services/archives-nationales-hydat.html
              hreflang: fr-CA
            - type: application/zip
              rel: download
              title: download data
              href: http://collaboration.cmc.ec.gc.ca/cmc/hydrometrics/www/Hydat_sqlite3_20180417.zip
              hreflang: en-CA
        extents:
            spatial:
                bbox: [-142, 52, -52, 84]
            temporal:
                begin: 1850-01-01
                end: now  # or empty
        provider:
            name: Elasticsearch
            data: http://localhost:9200/hydrometric_annual_statistics/FeatureCollection
            id_field: IDENTIFIER

    hydrometric-annual-peaks:
        title: Annual Maximum and Minimum Instantaneous Water Level or Flow
        description: The annual maximum and minimum instantaneous data are the maximum and minimum instantaneous values for a given year.
        keywords: [Annual maximum, Annual Minimum, Water Level, Flow, Discharge]
        crs:
            - CRS84
        links:
            - type: text/html
              rel: canonical
              title: Water Level and Flow - Environment Canada
              href: https://wateroffice.ec.gc.ca
              hreflang: en-CA
            - type: text/html
              rel: canonical
              title: Niveau d'eau et débit - Environnement Canada
              href: https://wateroffice.ec.gc.ca/index_f.html
              hreflang: fr-CA
            - type: text/html
              rel: download
              title: "National water data archive: HYDAT - Canada.ca"
              href: https://www.canada.ca/en/environment-climate-change/services/water-overview/quantity/monitoring/survey/data-products-services/national-archive-hydat.html
              hreflang: en-CA
            - type: text/html
              rel: download
              title: "Archives nationales des données hydrologiques : HYDAT - Canada.ca"
              href: https://www.canada.ca/fr/environnement-changement-climatique/services/eau-apercu/volume/surveillance/releves/produits-donnees-services/archives-nationales-hydat.html
              hreflang: fr-CA
            - type: application/zip
              rel: download
              title: download data
              href: http://collaboration.cmc.ec.gc.ca/cmc/hydrometrics/www/Hydat_sqlite3_20180417.zip
              hreflang: en-CA
        extents:
            spatial:
                bbox: [-142, 52, -52, 84]
            temporal:
                begin: 1850-01-01
                end: now  # or empty
        provider:
            name: Elasticsearch
            data: http://localhost:9200/hydrometric_annual_peaks/FeatureCollection
            id_field: IDENTIFIER
